### ISSUE TITLE
Backward PDDL ver. compatibility

### ISSUE THREAD

**Issue by weightle55** [KCL-Planning/SMTPlan#2]
Hello all,

I am wondering if SMTPlan+ supports backward compatibility from PDDL2.x to PDDL3.x.
The problem I am facing now is that SMTPlan+ works well for the sample programs under benchmark directory such as car_nodrag and generator_linear examples. However, SMTPlan+ doesn't works for the sample PDDL codes in PDDL2.1 or PDDL2.2 at ICAPS home page. Thus, when I run SMTPlan+ with the given example PDDL named airport I got the following error messages:

cyi@cyi:~/SMTPlan/SMTPlan/build$ ./SMTPlan P01_DOMAIN.PDDL P01_AIRPORT_P1.PDDL
terminate called after throwing an instance of 'VAL::ParseFailure'
  what():  Parser failed to read file!

Aborted (core dumped)

Could anyone out there give me any hints?

**Comment by m312z** [comment]
VAL is the plan validator, which SMTPlan uses to parse the domain and problem file. It looks like the domain or problem file are malformed in some way. You can try to run the VAL validator on the files directly, which should provide more in-depth information about the error:
https://github.com/KCL-Planning/VAL

As a general answer, SMTPlan should work with any PDDL2.x problem file, which is a subset of PDDL+. However, I don't think it will work with a PDDL3.x domain.

However, the planner's strengths are in handling continuous dynamics, and it does not scale very well as the discrete space gets larger. As a result, you might find the performance lacking in those domains.

Michael
